### ISSUE TITLE
Hello from docker dchen71/hla_prg_la

### ISSUE THREAD

**Issue by NTNguyen13** [dchen71/dchen71.github.io#3]
Hi, I find your HLA:PRG:LA docker on https://hub.docker.com/r/dchen71/hla_prg_la (I hope I'm not making a mistake). 

I have tried your docker, it run flawlessly. However I don't know where the output file is located?
My command is:
```
file=/home/nguyen/Data/BAM/VN_01_01_0411_01_01.bam
sample_name=VN_01_01_0411_01_01
docker run -v `pwd`:`pwd` -v /home/nguyen/Exec/HLA-LA/Graph:/app/HLA-PRG-LA/graphs     dchen71/hla_prg_la ./HLA-PRG-LA.pl --bam $file --sampleID $sample_name --maxThreads 10 --graph PRG_MHC_GRCh38_withIMGT
```

Could you please help me on this problem? Many thanks!

**Comment by dchen71** [comment]
Hi, sorry I never got a notification. 

For this container, you need to specify a working directory mount and then have HLA-PRG-LA output to that working directory. I haven't tried this but it would be something like this:

```
file=/home/nguyen/Data/BAM/VN_01_01_0411_01_01.bam
output_dir=/home/nguyen/Data/BAM/output
sample_name=VN_01_01_0411_01_01
docker run -v `pwd`:`pwd` -v /home/nguyen/Exec/HLA-LA/Graph:/app/HLA-PRG-LA/graphs -v $output_dir:/output    dchen71/hla_prg_la ./HLA-PRG-LA.pl --bam $file --sampleID $sample_name --maxThreads 10 --graph PRG_MHC_GRCh38_withIMGT --workingDir /output
```

By default, the output is saved locally in the docker container in it's own predefined output location so you need to create the output mount.

If I remember correctly as well, I have the updated HLA-LA version which is 2-3 releases ahead but probably undocumented.

**Comment by NTNguyen13** [comment]
Yes, thank you for your answer
